#!/usr/bin/env bash

set -e

echo "==> Running ruff"
uv run --all-extras ruff check src tests

echo "==> Running pyright"
uv run --all-extras  pyright src tests

echo "==> Running mypy"
uv run --all-extras  mypy src tests

echo "==> Making sure it imports"
uv run --with-editable . python -c 'import http_snapshot'