name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+.post[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+[a-b][0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

jobs:
  build:
    name: Build the source tarball and the wheel
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: 0

      - name: Install uv (official Astral action)
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.8.9"
          enable-cache: true
          python-version: 3.9

      - name: UV build
        run: uv build
      - name: Archive packages
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  publish:
    name: Publish build artifacts to the PyPI
    needs: build
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Retrieve packages
        uses: actions/download-artifact@v4
      - name: Upload packages
        uses: pypa/gh-action-pypi-publish@release/v1

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: 0

      - name: Install uv (official Astral action)
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.8.9"
          enable-cache: true
          python-version: 3.9

      - name: Set up Python (using uv)
        run: uv python install

      - name: Prepare release notes
        run: uv tool run git-changelog --release-notes > release-notes.md

      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Create release with assets
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body_path: release-notes.md
